
# srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 8 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache bde --note 'only use bde cache' --maintain_OH same
# srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 9 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache ip --note 'only use ip cache' --maintain_OH same
# srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 10 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache bde ip --note 'use bde ip cache' --maintain_OH same
# srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 11 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache --note 'no cache' --maintain_OH same

srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 12 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache bde --note 'only use bde cache' --maintain_OH same -ec 128 -eu 128
srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 13 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache ip --note 'only use ip cache' --maintain_OH same -ec 128 -eu 128
srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 14 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache bde ip --note 'use bde ip cache' --maintain_OH same -ec 128 -eu 128
srun --ntasks-per-node 16 -N 4 -p cypress_a100_night --account=app -u python main_dist.py --trial 15 --experiment hpc --iteration 2500 --init_mol_path ./Data/aodb_20.txt --gpu_list 0 1 2 3 --num_init_mol 256 --starter slurm --eps_decay 0.968 --max_steps_per_episode 10 --max_batch_size 512 --cache --note 'no cache' --maintain_OH same -ec 128 -eu 128

